services:
    database:
        image: postgres
        ports:
            - '5432:5432'

        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 0000
            POSTGRES_DB: ecommerce
volumes:
    pgdata:
