name: Build and deploy JAR app to Azure Web App

env:
    AZURE_WEBAPP_NAME: localshopper
    JAVA_VERSION: '17'
    DISTRIBUTION: temurin

on:
    push:
        branches: ['master', 'main']
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set environment variables
              run: |
                  echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
                  echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
                  echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
                  echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
                  echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
                  echo "AWS_ENDPOINT_URL=${{ secrets.AWS_ENDPOINT_URL }}" >> $GITHUB_ENV
                  echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
                  echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> $GITHUB_ENV
                  echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> $GITHUB_ENV

            - name: Set up Java version
              uses: actions/setup-java@v4
              with:
                  java-version: ${{ env.JAVA_VERSION }}
                  distribution: ${{ env.DISTRIBUTION }}
                  cache: 'maven'

            - name: Build with Maven
              run: mvn clean package -DskipTests

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: localshopper
                  path: localecommerce/target/*.jar

    deploy:
        permissions:
            contents: none
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: localshopper

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: '*.jar'
